name: fastfinder_build

on: [push, pull_request]

jobs:
  linux_standard-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            unzip \
            autoconf \
            automake \
            gcc-multilib \
            libtool \
            libjansson-dev \
            libmagic-dev \
            libssl-dev  \
            protobuf-compiler \
            protobuf-c-compiler \
            libprotobuf-c-dev \ 
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.17
      - name: Install YARA v4.1
        run: |
           wget -c https://github.com/VirusTotal/yara/archive/refs/tags/v4.1.3.zip -O /tmp/yara.zip
           cd /tmp && unzip yara.zip
           cd /tmp/yara-4.1.3
           ./configure && make && make install && make check
      - uses: actions/checkout@v2
      - name: Building Fastfinder
        run: |
           cd $GITHUB_WORKSPACE
           go build go build -tags yara_static -a -ldflags '-s -w' .
