name: fastfinder_build_linux

on: [push, pull_request]

jobs:
  linux_standard-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            unzip \
            automake \
            libtool \
            make \
            gcc \
            pkg-config
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.17
      - name: Install YARA v4.1
        run: |
           wget -c https://github.com/VirusTotal/yara/archive/refs/tags/v4.1.3.zip -O /tmp/yara.zip
           cd /tmp && unzip yara.zip
           cd /tmp/yara-4.1.3
           sudo ./bootstrap.sh
           sudo ./configure
           sudo make
           sudo make install
      - uses: actions/checkout@v2
      - name: Building Fastfinder
        run: |
           cd $GITHUB_WORKSPACE
           go build -a -ldflags "-s -w" .
           ls
           sudo chmod +x fastfinder
           sudo ./fastfinder -h
