name: fastfinder_build_linux

on: [push, pull_request]

jobs:
  linux_standard-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            bison \
            flex \
            autoconf \
            pkg-config \
            automake \
            libtool \
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.17
      - name: Install YARA v4.1
        run: |
          YARA_VERSION=4.1.3
          wget --no-verbose -O- https://github.com/VirusTotal/yara/archive/v${YARA_VERSION}.tar.gz | tar -C .. -xzf -
          ( cd ../yara-${YARA_VERSION} && ./bootstrap.sh )
          mkdir -p ../yara-build
          ( cd ../yara-build && \
          ../yara-${YARA_VERSION}/configure --disable-shared --prefix=${HOME}/prefix )
          make -C ../yara-build install
          find ${HOME}/prefix
      - uses: actions/checkout@v2
      - name: Building Fastfinder
        run: |
           export CGO_CFLAGS="-I${HOME}/../yara-${YARA_VERSION}/libyara/include"
           export CGO_LDFLAGS="-L${HOME}/../yara-${YARA_VERSION}/libyara/.libs -lyara"
           go build -a -tags yara_no_pkg_config -ldflags "-s -w" .
           ls
           sudo chmod +x fastfinder
           sudo ./fastfinder -h
