name: fastfinder_build_windows

on: [push, pull_request]

jobs:
  windows_standard-build:
    runs-on: windows-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.17
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          path-type: inherit
          update: true
          install: mingw-w64-x86_64-toolchain mingw-w64-x86_64-pkg-config base-devel openssl-devel
      - shell: msys2 {0}
      - name: Compile YARA v4.1 from MSYS2
        run: |
             wget -c https://github.com/VirusTotal/yara/archive/refs/tags/v4.1.3.zip -O /tmp/yara.zip
             cd /tmp && unzip yara.zip
             cd /tmp/yara-4.1.3
             ./bootstrap.sh
             ./configure
             make
             make install
      - shell: powershell
      - name: Configuring environment variables and CGO flags
        run: |
          set GOOS=windows
          set GOARCH=amd64
          set CGO_CFLAGS=-IC:/msys64/mingw64/include
          set CGO_LDFLAGS=-LC:/msys64/mingw64/lib -lyara -lcrypto
      - uses: actions/checkout@v2
      - name: Building Fastfinder
        run: |
           cd $GITHUB_WORKSPACE
           go build -tags yara_static -a -ldflags '-s -w -extldflags "-static"' .
