name: fastfinder_build

on: [push, pull_request]

jobs:
  windows_standard-build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          path-type: minimal
          update: true
          install: mingw-w64-x86_64-toolchain mingw-w64-x86_64-pkg-config base-devel openssl-devel unzip
      - name: Install YARA v4.1
        run: |
             wget -c https://github.com/VirusTotal/yara/archive/refs/tags/v4.1.3.zip -O /tmp/yara.zip
             cd /tmp && unzip yara.zip
             cd /tmp/yara-4.1.3
             ./bootstrap.sh
             ./configure
             make
             make install
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.17
      - name: Configuring environment variables and CGO flags
        run: |
          set GOOS=windows
          set GOARCH=amd64
          set CGO_CFLAGS=-IC:/msys64/mingw64/include
          set CGO_LDFLAGS=-LC:/msys64/mingw64/lib -lyara -lcrypto
      - uses: actions/checkout@v2
      - name: Building Fastfinder
        run: |
           powershell -c 'cd $GITHUB_WORKSPACE && go build -tags yara_static -a -ldflags \'-s -w -extldflags "-static"\' .'
